apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus-2
  name: girus-2
spec:
  containers:
  - image: ngnix
    name: girus-2
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
